---
title: "Untitled"
author: "Dmitrii"
date: "15 апреля 2015 г."
output: ioslides_presentation
runtime: shiny
---

## Метод K-средних
```{r, fig.align='center', echo=F}
readBank <- function(){
bankruptcy <- read.csv(file="pred.csv",stringsAsFactors = FALSE, header=TRUE, sep=";", dec= ".")
for (i in 2:7) bankruptcy[,i]  <- as.numeric(as.character(bankruptcy[,i]))
bankruptcy <- bankruptcy[ which(bankruptcy$Автономность < 30 ), ]
bankruptcy <- bankruptcy[ which(bankruptcy$Рентабельность.активов > -6), ]
bankruptcy <- bankruptcy[ which(bankruptcy$Доходность.активов > -6), ]
bankruptcy <- bankruptcy[ which(bankruptcy$Оборачиваемость.активов < 10), ]
bankruptcy <- bankruptcy[ which(bankruptcy$Доходность.активов > -6), ]
bankruptcy <- bankruptcy[-c(1,195),]
rownames(bankruptcy) <- NULL
return(bankruptcy)
}
bankruptcy <- readBank();
bankruptcy_backup <- bankruptcy;
ind1 <- subset(bankruptcy, bankruptcy[,"Банкрот"]==1, select=ID: Банкрот)
ind0 <- subset(bankruptcy, bankruptcy[,"Банкрот"]==0, select=ID: Банкрот)
sampind1 <- ind1[sample(1:nrow(ind1), 53, replace=FALSE),]
sampind0 <- ind0[sample(1:nrow(ind0), 158, replace=FALSE),]

training_data <- rbind(sampind0, sampind1)
testing_data <- bankruptcy[!(bankruptcy$ID %in% training_data$ID),]
rownames(training_data)<-NULL
rownames(testing_data)<-NULL
rm(ind0, ind1, sampind0, sampind1)
clear_test <- subset(testing_data, select=Ликвидность.активов:Банкрот)

training_data_backup <- training_data;
testing_data_backup <- testing_data;
clear_test_backup <- clear_test;

training_data <- NULL
testing_data <- NULL
training_data$values <- training_data_backup
training_data$Банкрот <- training_data$values$Банкрот
testing_data$values <- testing_data_backup
testing_data$Банкрот <- testing_data$values$Банкрот
training_data$values$Банкрот <- NULL
testing_data$values$Банкрот <- NULL
training_data$values$ID <- NULL
testing_data$values$ID <- NULL
for (i in 2:5) training_data$values[,i] <- 1/(1+(exp(-1*training_data$values[,i])))
for (i in 2:5) testing_data$values[,i] <- 1/(1+(exp(-1*testing_data$values[,i])))

bank <- (nrow(training_data$values) -1)*sum(apply(training_data$values, 2,var))
for (i in 2:20) bank[i]  <- sum(kmeans(training_data$values, center = i)$withinss)
x<-1:20
```

Следует выбрать такое количество кластеров, при котором, добавление очередного кластера не придаст значительных улучшений в моделировании данных. 

```{r, echo=F}
renderPlot({
plot(x, bank, type="b", xlab='Количество кластеров', ylab='Дисперсия случайной величины', col=ifelse(x==5, "red", "black"),
     pch=ifelse(x==5, 19, 1))
axis(side=1, at=c(0:20))
})


nr <- NROW(training_data$values)
#ind <- sample(nr, 0.9 * nr, replace = FALSE)
party <- kmeans(training_data$values, 5)
```

## Диаграммы рассеивания
```{r, echo=F}

#lets see what we got

  numericInput("km_clusters", 
        label = h5("Количество кластеров"), 
        value = 5)
  

renderPlot({
  party <- kmeans(training_data$values, input$km_clusters)
  plot(training_data$values, col=party$cluster)
})
```

## Сравнение


```{r, echo=F,message=FALSE}
library(clue)


showclustables <- function(){
shinyApp(
  ui = fluidPage(
    fluidRow(column(3,numericInput("kmnumclusters", 
        label = h5("Количество кластеров"), 
        value = 5))),
    fluidRow(
    dataTableOutput('firsttable')
  ),fluidRow(
    dataTableOutput('secondtable')
  )
  ),
  server = function(input, output) {
    clusc <- reactive({
      clusc <- input$kmnumclusters
    })
    
    output$firsttable = renderDataTable({
      party<-kmeans(training_data$values,clusc())
      kmeans_test <- cl_predict(party, training_data$values)
kmeans_test_res <- as.data.frame(table(cluster = kmeans_test, "Банкрот" = training_data$Банкрот))
kn<-(NROW(kmeans_test_res)/2)
kmeans_test_rest <- kmeans_test_res[1:kn,]
kmeans_test_rest$Банкрот <-NULL
colnames(kmeans_test_rest)<-c('№ кластера','Не банкрот')
kn1<-kn+1
kn2<-NROW(kmeans_test_res)
kmeans_test_rest$'Банкрот' <- kmeans_test_res[kn1:kn2,3]
kmeans_test_rest$'Доля банкротов от общего числа (в %)' <- round(kmeans_test_rest$'Банкрот'/(kmeans_test_rest$'Не банкрот' + kmeans_test_rest$'Банкрот')*100,digits=2)
kmeans_test_res<-kmeans_test_rest
firstTable <- kmeans_test_res
kmeans_predict<- cl_predict(party, testing_data$values)
kmeans_test_res <- as.data.frame(table(cluster = kmeans_predict, "Банкрот" = testing_data$Банкрот))
kn<-(NROW(kmeans_test_res)/2)
kmeans_test_rest <- kmeans_test_res[1:kn,]
kmeans_test_rest$Банкрот <-NULL
colnames(kmeans_test_rest)<-c('№ кластера','Не банкрот')
kn1<-kn+1
kn2<-NROW(kmeans_test_res)
kmeans_test_rest$'Банкрот' <- kmeans_test_res[kn1:kn2,3]
kmeans_test_rest$'Доля банкротов от общего числа (в %)' <- round(kmeans_test_rest$'Банкрот'/(kmeans_test_rest$'Не банкрот' + kmeans_test_rest$'Банкрот')*100,digits=2)
kmeans_test_res<-kmeans_test_rest
      firstTable
    },options = list(searching = FALSE, paging = FALSE))
    output$secondtable = renderDataTable({
      party<-kmeans(training_data$values,clusc())
      kmeans_test <- cl_predict(party, training_data$values)
kmeans_test_res <- as.data.frame(table(cluster = kmeans_test, "Банкрот" = training_data$Банкрот))
kn<-(NROW(kmeans_test_res)/2)
kmeans_test_rest <- kmeans_test_res[1:kn,]
kmeans_test_rest$Банкрот <-NULL
colnames(kmeans_test_rest)<-c('№ кластера','Не банкрот')
kn1<-kn+1
kn2<-NROW(kmeans_test_res)
kmeans_test_rest$'Банкрот' <- kmeans_test_res[kn1:kn2,3]
kmeans_test_rest$'Доля банкротов от общего числа (в %)' <- round(kmeans_test_rest$'Банкрот'/(kmeans_test_rest$'Не банкрот' + kmeans_test_rest$'Банкрот')*100,digits=2)
kmeans_test_res<-kmeans_test_rest
firstTable <- kmeans_test_res
kmeans_predict<- cl_predict(party, testing_data$values)
kmeans_test_res <- as.data.frame(table(cluster = kmeans_predict, "Банкрот" = testing_data$Банкрот))
kn<-(NROW(kmeans_test_res)/2)
kmeans_test_rest <- kmeans_test_res[1:kn,]
kmeans_test_rest$Банкрот <-NULL
colnames(kmeans_test_rest)<-c('№ кластера','Не банкрот')
kn1<-kn+1
kn2<-NROW(kmeans_test_res)
kmeans_test_rest$'Банкрот' <- kmeans_test_res[kn1:kn2,3]
kmeans_test_rest$'Доля банкротов от общего числа (в %)' <- round(kmeans_test_rest$'Банкрот'/(kmeans_test_rest$'Не банкрот' + kmeans_test_rest$'Банкрот')*100,digits=2)
kmeans_test_res<-kmeans_test_rest
      kmeans_test_res
    },options = list(searching = FALSE, paging = FALSE))
  }
)
}
showclustables()
```

## 3d

```{r,echo=F,message=F}
library(Cairo)
options(shiny.usecairo=T)
options(rgl.useNULL=TRUE)
library("shinyRGL")
library("rgl")
 kdd <- function() {
  shinyApp(
    ui = fluidPage(
      fluidRow(column(3,numericInput("kmnumclusters", 
        label = h5("Количество кластеров"), 
        value = 5))),
      fluidRow( webGLOutput("mykdd"))     
    ),
    server = function(input, output, session) {
      clusc <- reactive({
            clusc <- input$kmnumclusters
          })
      output$mykdd <- renderWebGL({
          party<-kmeans(training_data$values,clusc())
         plot3d(training_data$values[,c(1,4,5)], col=party$cluster)
      })
    },
    options = list(height = 700)
  )
}
kdd()
```
